from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from .config import DATA_DIR, FEATURE_COLUMNS, MODELS_DIR, OUTPUTS_DIR, TARGET_COLUMN
from .features import split_features_target
from .models import EXPERIMENTS, build_model, import_tensorflow, training_callbacks


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train ANN heuristic experiments.")
    parser.add_argument(
        "--dataset",
        type=Path,
        default=DATA_DIR / "maze_dataset.csv",
        help="CSV generated by src.generate_dataset.",
    )
    parser.add_argument(
        "--experiment",
        choices=["underfit", "overfit", "goodfit", "all"],
        default="all",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--models-dir", type=Path, default=MODELS_DIR)
    parser.add_argument("--outputs-dir", type=Path, default=OUTPUTS_DIR)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.models_dir.mkdir(parents=True, exist_ok=True)
    args.outputs_dir.mkdir(parents=True, exist_ok=True)

    if not args.dataset.exists():
        raise FileNotFoundError(
            f"Dataset not found: {args.dataset}. Run `python -m src.generate_dataset` first."
        )

    df = pd.read_csv(args.dataset)
    missing_columns = set(FEATURE_COLUMNS + [TARGET_COLUMN]) - set(df.columns)
    if missing_columns:
        raise ValueError(f"Dataset is missing columns: {sorted(missing_columns)}")

    experiments = list(EXPERIMENTS) if args.experiment == "all" else [args.experiment]
    metrics = {}

    for experiment in experiments:
        print(f"\n=== Training {experiment} ===")
        metrics[experiment] = run_experiment(
            experiment=experiment,
            df=df,
            seed=args.seed,
            models_dir=args.models_dir,
            outputs_dir=args.outputs_dir,
        )

    summary_path = args.outputs_dir / "training_summary.json"
    summary_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(f"\nSaved summary: {summary_path}")


def run_experiment(
    experiment: str,
    df: pd.DataFrame,
    seed: int,
    models_dir: Path,
    outputs_dir: Path,
) -> dict[str, float | int | str]:
    config = EXPERIMENTS[experiment]
    train_df, val_df, test_df = split_dataframe(df, seed=seed)

    if config.train_limit is not None and len(train_df) > config.train_limit:
        train_df = train_df.sample(n=config.train_limit, random_state=seed)

    x_train, y_train = split_features_target(train_df)
    x_val, y_val = split_features_target(val_df)
    x_test, y_test = split_features_target(test_df)

    model = build_model(experiment, input_dim=x_train.shape[1])
    print(config.description)
    model.summary()

    history = model.fit(
        x_train,
        y_train,
        validation_data=(x_val, y_val),
        epochs=config.epochs,
        batch_size=config.batch_size,
        callbacks=training_callbacks(experiment),
        verbose=2,
    )

    evaluation = model.evaluate(x_test, y_test, verbose=0, return_dict=True)
    predictions = model.predict(x_test, verbose=0).reshape(-1)
    test_mae = mean_absolute_error(y_test, predictions)
    test_mse = mean_squared_error(y_test, predictions)

    model_path = models_dir / f"ann_heuristic_{experiment}.keras"
    tflite_path = models_dir / f"ann_heuristic_{experiment}.tflite"
    history_path = outputs_dir / f"{experiment}_history.csv"
    plot_path = outputs_dir / f"{experiment}_loss.png"
    metrics_path = outputs_dir / f"{experiment}_metrics.json"

    model.save(model_path)

    # Convert and save TFLite model
    tf = import_tensorflow()
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
    tflite_path.write_bytes(tflite_model)

    history_to_dataframe(history).to_csv(history_path, index=False)
    plot_training_history(history, plot_path, title=f"{experiment.title()} Loss")

    metrics = {
        "experiment": experiment,
        "train_rows": int(len(train_df)),
        "validation_rows": int(len(val_df)),
        "test_rows": int(len(test_df)),
        "epochs_ran": int(len(history.history["loss"])),
        "test_loss_mse": float(evaluation["loss"]),
        "test_mae_from_keras": float(evaluation["mae"]),
        "test_mae": float(test_mae),
        "test_mse": float(test_mse),
        "model_path": str(model_path),
        "tflite_path": str(tflite_path),
        "history_path": str(history_path),
        "plot_path": str(plot_path),
    }
    metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")

    print(f"Saved model: {model_path}")
    print(f"Saved plot: {plot_path}")
    print(f"Test MAE: {test_mae:.3f} steps")
    return metrics


def split_dataframe(
    df: pd.DataFrame,
    seed: int,
    train_ratio: float = 0.70,
    val_ratio: float = 0.15,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    shuffled = df.sample(frac=1.0, random_state=seed).reset_index(drop=True)
    train_end = int(len(shuffled) * train_ratio)
    val_end = train_end + int(len(shuffled) * val_ratio)
    return shuffled.iloc[:train_end], shuffled.iloc[train_end:val_end], shuffled.iloc[val_end:]


def history_to_dataframe(history) -> pd.DataFrame:
    rows = []
    for epoch_index in range(len(history.history["loss"])):
        row = {"epoch": epoch_index + 1}
        for key, values in history.history.items():
            row[key] = float(values[epoch_index])
        rows.append(row)
    return pd.DataFrame(rows)


def plot_training_history(history, output_path: Path, title: str) -> None:
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise RuntimeError(
            "matplotlib is required to save training plots. Install requirements first."
        ) from exc

    epochs = np.arange(1, len(history.history["loss"]) + 1)

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    axes[0].plot(epochs, history.history["loss"], label="Train loss")
    axes[0].plot(epochs, history.history["val_loss"], label="Validation loss")
    axes[0].set_title(title)
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("MSE loss")
    axes[0].legend()
    axes[0].grid(alpha=0.3)

    axes[1].plot(epochs, history.history["mae"], label="Train MAE")
    axes[1].plot(epochs, history.history["val_mae"], label="Validation MAE")
    axes[1].set_title("MAE")
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Steps")
    axes[1].legend()
    axes[1].grid(alpha=0.3)

    fig.tight_layout()
    fig.savefig(output_path, dpi=160)
    plt.close(fig)


def mean_absolute_error(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.mean(np.abs(y_true - y_pred)))


def mean_squared_error(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.mean(np.square(y_true - y_pred)))


if __name__ == "__main__":
    main()
